name: dogs_images
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  build_runner: ^2.4.6
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.4
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  mockito: ^5.4.2
  photo_view: ^0.14.0
  shimmer: ^3.0.0
flutter_native_splash:
  color: "#ffffff"
  image: assets/imgs/dogg.jpg
  # imageFit: fill
  # fill: true
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
